/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.PhieuMuon;

import Controllers.ClassColorTable;
import Controllers.ControllerPhieuMuon;
import Models.BanDoc;
import Views.PanelMainBanDoc;
import java.awt.Component;
import java.awt.Point;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Huy Thắng
 */
public class PanelPhieuMuonBanDoc extends javax.swing.JPanel {

    ControllerPhieuMuon cpm;
    BanDoc bandoc;
    PanelMainBanDoc pmbd;

    /**
     * Creates new form PanelPhieuMuonBanDoc
     */
    public PanelPhieuMuonBanDoc(BanDoc bandoc, PanelMainBanDoc pmbd) {
        initComponents();
        this.bandoc = bandoc;
        this.pmbd = pmbd;
        TableSach.setDefaultRenderer(Object.class, new ClassColorTable());
        cpm = new ControllerPhieuMuon();
        LoadingData();
    }

    public void LoadingData() {
        long trangsach = Long.parseLong(TrangSach.getText());
        cpm.VeTablePMBanDoc(TableSach, trangsach, TacGiaSach, bandoc.getMaBanDoc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TacGiaSach = new javax.swing.JComboBox<>();
        NhanTimKiemTG5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableSach = new org.jdesktop.swingx.JXTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);
                int rendererWidth = component.getPreferredSize().width;
                TableColumn tableColumn = getColumnModel().getColumn(column);
                tableColumn.setPreferredWidth(Math.max(rendererWidth + getIntercellSpacing().width, tableColumn.getPreferredWidth()));
                return component;
            }
        };
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TrangSach = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(700, 545));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TacGiaSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TacGiaSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Đang Mượn", "Đã Trả", "Quá Hạn", "Quá Hạn + Mất Sách", "Mất sách" }));
        TacGiaSach.setMinimumSize(new java.awt.Dimension(158, 30));
        TacGiaSach.setPreferredSize(new java.awt.Dimension(158, 30));
        TacGiaSach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TacGiaSachItemStateChanged(evt);
            }
        });
        add(TacGiaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 38, 244, 30));

        NhanTimKiemTG5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NhanTimKiemTG5.setForeground(new java.awt.Color(255, 255, 255));
        NhanTimKiemTG5.setText("Trạng Thái Phiếu Mượn:");
        add(NhanTimKiemTG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 38, 175, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, 696, 80));

        TableSach.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableSach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TableSach.setRowHeight(30);
        TableSach.setShowGrid(true);
        TableSach.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableSach.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                }
            }
        );
        TableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableSachMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(TableSach);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 680, 362));

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/first.png"))); // NOI18N
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 496, -1, -1));

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/back.png"))); // NOI18N
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 496, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trang");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 496, 50, 30));

        TrangSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TrangSach.setForeground(new java.awt.Color(255, 255, 255));
        TrangSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TrangSach.setText("1");
        TrangSach.setPreferredSize(new java.awt.Dimension(20, 30));
        add(TrangSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 496, 20, -1));

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/next.png"))); // NOI18N
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 496, -1, -1));

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/last.png"))); // NOI18N
        jLabel64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 496, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Danh Sách Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 92, 696, 453));
        add(wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 545));
    }// </editor-fold>//GEN-END:initComponents

    private void TacGiaSachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TacGiaSachItemStateChanged
        // TODO add your handling code here:
        TrangSach.setText("1");
        LoadingData();
    }//GEN-LAST:event_TacGiaSachItemStateChanged

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        // TODO add your handling code here:
        cpm.FirstButtonBanDoc(TableSach, TacGiaSach, bandoc.getMaBanDoc(), TrangSach);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        // TODO add your handling code here:
        cpm.PreButtonBanDoc(TableSach, TacGiaSach, bandoc.getMaBanDoc(), TrangSach);
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
        cpm.NextButtonBanDoc(TableSach, TacGiaSach, bandoc.getMaBanDoc(), TrangSach);
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        // TODO add your handling code here:
        cpm.LastButtonBanDoc(TableSach, TacGiaSach, bandoc.getMaBanDoc(), TrangSach);
    }//GEN-LAST:event_jLabel64MouseClicked

    private void TableSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMousePressed
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int row = table.rowAtPoint(p);
        if (evt.getClickCount() == 2) {
            cpm.ChiTietPMBanDoc(TableSach,pmbd);
        }
    }//GEN-LAST:event_TableSachMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NhanTimKiemTG5;
    private org.jdesktop.swingx.JXTable TableSach;
    public static javax.swing.JComboBox<String> TacGiaSach;
    private javax.swing.JLabel TrangSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
