/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Controller;
import Controllers.SetWallpaper;
import Models.BanDoc;

/**
 *
 * @author Huy Thắng
 */
public class PanelChangeMK extends javax.swing.JDialog {

    int xMouse;
    int yMouse;
    boolean check = true;
    BanDoc bd;
    Controller cl;

    /**
     * Creates new form PanelChangeMK
     */
    public PanelChangeMK(java.awt.Frame parent, boolean modal, boolean check) {
        super(parent, modal);
        initComponents();
        this.check = check;
        cl = new Controller();
        SetWallpaper sw= new SetWallpaper();
        sw.SetWallpaper470x400(wall2);
    }

    public PanelChangeMK(java.awt.Frame parent, boolean modal, BanDoc bd, boolean check) {
        super(parent, modal);
        initComponents();
        this.check = check;
        this.bd = bd;
        cl = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passcu = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        login1 = new javax.swing.JButton();
        wall2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Libary manager");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/newpass.png"))); // NOI18N
        jLabel6.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 450, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mật Khẩu Hiện Tại:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 30));

        passcu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passcu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(passcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 410, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mật khẩu Mới:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, 340, 30));

        pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 215, 410, 30));

        pass1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 410, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nhập Lại Mật Khẩu Mới:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));

        login.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/thoat_1.png"))); // NOI18N
        login.setText("Thoát");
        login.setFocusable(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 345, 130, 40));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/Resert.png"))); // NOI18N
        reset.setText("Làm Lại");
        reset.setFocusable(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 345, 130, 40));

        login1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/edit.png"))); // NOI18N
        login1.setText("Thay Đổi");
        login1.setFocusable(false);
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        getContentPane().add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 345, 130, 40));

        wall2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screen/gray-15.png"))); // NOI18N
        wall2.setMaximumSize(new java.awt.Dimension(470, 400));
        wall2.setMinimumSize(new java.awt.Dimension(470, 400));
        wall2.setPreferredSize(new java.awt.Dimension(470, 400));
        getContentPane().add(wall2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 400));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        passcu.setText("");
        pass.setText("");
        pass1.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        if (check == false) {
            cl.chaneMKAdmin(passcu, pass, pass1, this);
        } else {
            cl.chaneMKBanDoc(passcu, pass, pass1, bd, this);
        }
    }//GEN-LAST:event_login1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField passcu;
    private javax.swing.JButton reset;
    private javax.swing.JLabel wall2;
    // End of variables declaration//GEN-END:variables
}
