/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.BanDoc;

import Controllers.ControllerBanDoc;
import Controllers.ControllerCheck;
import Controllers.SetWallpaper;
import Models.BanDoc;
import Views.PanelMainAdmin;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Huy Thắng
 */
public class PanelEditBanDoc extends javax.swing.JDialog {

    String filePath = "";
    int xMouse;
    int yMouse;
    PanelMainAdmin pma;
    BanDoc bd;
    ControllerBanDoc cbd;

    /**
     * Creates new form NewJDialog
     */
    public PanelEditBanDoc(java.awt.Frame parent, boolean modal, BanDoc bd) {
        super(parent, modal);
        initComponents();
        this.bd = bd;
        cbd = new ControllerBanDoc();
        cbd.SetEditBD(bd, mabd, hoten, ngaysinh, gioitinh, diachi, user, cmnd, tel, email, tiencuoc, tinhtrang, ngaylam, ngayhet, labelAnh);
        SetWallpaper sw = new SetWallpaper();
        sw.SetWallpaper630x590(walsetdb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mabd = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ngaysinh = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        gioitinh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diachi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tiencuoc = new javax.swing.JLabel();
        tiencuoc1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tinhtrang = new javax.swing.JComboBox<>();
        lephi = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ngaylam = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ngayhet = new javax.swing.JLabel();
        labelAnh = new javax.swing.JLabel();
        chonanh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        walsetdb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 590));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(630, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Libary manager");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT BẠN ĐỌC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 570, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã bạn đọc:");
        jLabel3.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 30));

        mabd.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mabd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mabd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Họ tên bạn đọc:");
        jLabel10.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        hoten.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        hoten.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ngày sinh:");
        jLabel11.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        ngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        ngaysinh.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Giới tính:");
        jLabel13.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        gioitinh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        gioitinh.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Địa chỉ:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 30));

        diachi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 460, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tên đăng nhập:");
        jLabel15.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel15.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel15.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 30));

        user.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setMaximumSize(new java.awt.Dimension(110, 30));
        user.setMinimumSize(new java.awt.Dimension(110, 30));
        user.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CMND");
        jLabel14.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel14.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel14.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 30));

        cmnd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(cmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 180, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Điện thoại:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, 30));

        tel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 180, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email:");
        jLabel16.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 90, 30));

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 180, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tiền cược:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 30));

        tiencuoc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tiencuoc.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tiencuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 100, 30));

        tiencuoc1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tiencuoc1.setForeground(new java.awt.Color(255, 255, 255));
        tiencuoc1.setText("VND");
        getContentPane().add(tiencuoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 70, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tình trạng:");
        jLabel18.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel18.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel18.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, 30));

        tinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hết Hạn", "Còn Hạn" }));
        getContentPane().add(tinhtrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 180, 30));

        lephi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lephi.setForeground(new java.awt.Color(255, 255, 255));
        lephi.setMaximumSize(new java.awt.Dimension(110, 30));
        lephi.setMinimumSize(new java.awt.Dimension(110, 30));
        lephi.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(lephi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 180, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ngày làm thẻ:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 30));

        ngaylam.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        ngaylam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ngaylam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 180, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hạn thẻ:");
        jLabel21.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel21.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel21.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 90, 30));

        ngayhet.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        ngayhet.setForeground(new java.awt.Color(255, 255, 255));
        ngayhet.setMaximumSize(new java.awt.Dimension(110, 30));
        ngayhet.setMinimumSize(new java.awt.Dimension(110, 30));
        ngayhet.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(ngayhet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 180, 30));

        labelAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(labelAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 90, 114, 151));

        chonanh.setText("Chọn");
        chonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhActionPerformed(evt);
            }
        });
        getContentPane().add(chonanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 80, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/edit.png"))); // NOI18N
        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 535, 100, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/lamlai.png"))); // NOI18N
        jButton2.setText("Làm lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 535, 110, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/thoat_1.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 535, 100, -1));

        walsetdb.setMaximumSize(new java.awt.Dimension(630, 590));
        walsetdb.setMinimumSize(new java.awt.Dimension(630, 590));
        walsetdb.setPreferredSize(new java.awt.Dimension(630, 590));
        getContentPane().add(walsetdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 590));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fillter = new FileNameExtensionFilter("Image file", ImageIO.getReaderFileSuffixes());
        fileChooser.setFileFilter(fillter);
        fileChooser.setMultiSelectionEnabled(false);
        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            File imgFile = fileChooser.getSelectedFile();
            filePath = imgFile.getAbsolutePath();
            labelAnh.setIcon(ControllerCheck.load(filePath, labelAnh.getWidth(), labelAnh.getHeight()));
        }
    }//GEN-LAST:event_chonanhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cbd.UpdateBDAdmin(cmnd, filePath, diachi, tel, email, tinhtrang, bd.getMaBanDoc(), this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        filePath = "";
        cbd.SetEditBD(bd, mabd, hoten, ngaysinh, gioitinh, diachi, user, cmnd, tel, email, tiencuoc, tinhtrang, ngaylam, ngayhet, labelAnh);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chonanh;
    private javax.swing.JTextField cmnd;
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField email;
    private javax.swing.JLabel gioitinh;
    private javax.swing.JLabel hoten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelAnh;
    private javax.swing.JLabel lephi;
    private javax.swing.JLabel mabd;
    private javax.swing.JLabel ngayhet;
    private javax.swing.JLabel ngaylam;
    private javax.swing.JLabel ngaysinh;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel tiencuoc;
    private javax.swing.JLabel tiencuoc1;
    private javax.swing.JComboBox<String> tinhtrang;
    private javax.swing.JLabel user;
    public static javax.swing.JLabel walsetdb;
    // End of variables declaration//GEN-END:variables
}
