/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.NhanVien;

import Controllers.ControllerCheck;
import Controllers.ControllerNhanVien;
import Controllers.SetWallpaper;
import com.toedter.calendar.JTextFieldDateEditor;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Huy Thắng
 */
public class PanelNewNhanVien extends javax.swing.JDialog {

    private String filePath = "";
    int xMouse;
    int yMouse;

    /**
     * Creates new form PanelNewNhanVien
     */
    public PanelNewNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ngaytao.setText(ControllerCheck.DateNow());
        SetWallpaper sw = new SetWallpaper();
        sw.SetWallpaper630x550(walsetdb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hoten = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        gioitinh = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmnd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        diachi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dienthoai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tendangnhap = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ngaytao = new javax.swing.JLabel();
        phanquyen = new javax.swing.JComboBox<>();
        labelAnh = new javax.swing.JLabel();
        chonanh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        walsetdb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(630, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Libary manager");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM NHÂN VIÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ tên:");
        jLabel3.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 30));

        hoten.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày sinh:");
        jLabel10.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        JTextFieldDateEditor editor = (JTextFieldDateEditor) ngaysinh.getDateEditor();
        editor.setEditable(false);
        ngaysinh.setDateFormatString("dd-MM-yyyy");
        ngaysinh.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ngaysinh.setMaxSelectableDate(new java.util.Date(253370743297000L));
        ngaysinh.setMinSelectableDate(null);
        getContentPane().add(ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Giới tính:");
        jLabel11.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        gioitinh.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        getContentPane().add(gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CMND:");
        jLabel13.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        cmnd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Địa chỉ:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 30));

        diachi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 460, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Điện thoại:");
        jLabel15.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel15.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel15.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 30));

        dienthoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(dienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email:");
        jLabel14.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel14.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel14.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 30));

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 180, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên đăng nhập:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, 30));

        tendangnhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 180, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ngày tạo:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 90, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phân quyền");
        jLabel12.setMaximumSize(new java.awt.Dimension(110, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(110, 30));
        jLabel12.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 30));

        ngaytao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ngaytao.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ngaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 180, 30));

        phanquyen.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        phanquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Administrator" }));
        getContentPane().add(phanquyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 180, 30));

        labelAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/NoImages.png"))); // NOI18N
        labelAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(labelAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 90, 114, 151));

        chonanh.setText("Chọn");
        chonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhActionPerformed(evt);
            }
        });
        getContentPane().add(chonanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 80, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/Them.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 485, 130, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/lamlai.png"))); // NOI18N
        jButton2.setText("Làm lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 485, 110, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/thoat_1.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 485, 100, -1));

        walsetdb.setBackground(new java.awt.Color(0, 0, 0));
        walsetdb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        walsetdb.setMaximumSize(new java.awt.Dimension(630, 590));
        walsetdb.setMinimumSize(new java.awt.Dimension(630, 590));
        walsetdb.setOpaque(true);
        walsetdb.setPreferredSize(new java.awt.Dimension(630, 590));
        getContentPane().add(walsetdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 550));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fillter = new FileNameExtensionFilter("Image file", ImageIO.getReaderFileSuffixes());
        fileChooser.setFileFilter(fillter);
        fileChooser.setMultiSelectionEnabled(false);
        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            File imgFile = fileChooser.getSelectedFile();
            filePath = imgFile.getAbsolutePath();
            labelAnh.setIcon(ControllerCheck.load(filePath, labelAnh.getWidth(), labelAnh.getHeight()));
        }
    }//GEN-LAST:event_chonanhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ControllerNhanVien cnv = new ControllerNhanVien();
        cnv.NewNVAdmin(hoten, cmnd, filePath, diachi, dienthoai, email, ngaysinh, gioitinh, tendangnhap, phanquyen, this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hoten.setText("");
        ngaysinh.setCalendar(null);
        gioitinh.setSelectedIndex(0);
        cmnd.setText("");
        diachi.setText("");
        dienthoai.setText("");
        email.setText("");
        tendangnhap.setText("");
        phanquyen.setSelectedIndex(0);
        filePath = "";
        labelAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon/NoImages.png")));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chonanh;
    private javax.swing.JTextField cmnd;
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField dienthoai;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gioitinh;
    private javax.swing.JTextField hoten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelAnh;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JLabel ngaytao;
    private javax.swing.JComboBox<String> phanquyen;
    private javax.swing.JTextField tendangnhap;
    public static javax.swing.JLabel walsetdb;
    // End of variables declaration//GEN-END:variables
}
